export default [
    {
        id:1,
        image: '../../public/post1.png',
        name:'Wires'
    },
    {
        id:1,
        image:'../../assets/post2.png',
        name:'Wires'
    },
    {
        id:1,
        image:'../../assets/post2.png',
        name:'Wires'
    },
    {
        id:1,
        image:'../../assets/post2.png',
        name:'Wires'
    },
    {
        id:1,
        image:'../../assets/post2.png',
        name:'Wires'
    },
    {
        id:1,
        image:'../../assets/post2.png',
        name:'Wires'
    },
    {
        id:1,
        image:'../../assets/post2.png',
        name:'Wires'
    }
]